options:
  merge-default-rules: false
  formatter: stylish
  # Raise an error if more than 50 warnings are generated
  max-warnings: 50
# File Options
files:
  ignore:
    - 'scss/fonts/_icons.scss'
    - 'scss/_mixins.scss'
    - 'scss/_overrides.scss'
# Rule Configuration
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 0
  mixins-before-declarations:
    - 2
    -
      exclude:
        - media-breakpoint-up
  no-warn: 1
  no-debug: 1
  no-important: 0
  hex-notation:
    - 2
  indentation:
    - 2
    -
      size: 2