# Schema for the configuration files of the Sa11y module.
sa11y.settings:
  type: config_object
  label: 'Sa11y settings'
  mapping:
    api_server:
      type: string
      label: 'Your API server url'
    api_key:
      type: string
      label: 'Your assigned API key'
    rules:
      type: sequence
      label: 'Rules'
      sequence:
        type: string
        label: 'Rule'
    frequency:
      type: integer
      label: 'Freqeuency to run report'
    emails:
      type: sequence
      label: 'Email addresses to notify when updates are available'
      sequence:
        type: email
        label: 'Email'
